/**
 * Admin column structure — mirrors the source site (apigcl.com) XgxCms admin panel.
 * Each top-level section (pid) contains sub-categories (c_id) that map to either
 * static site-seed.json data or database-backed news categories.
 *
 * IMPORTANT (performance): this module must NOT import `@/lib/site`. That module
 * eagerly loads the 14 MB `site-seed.json`, which used to be inlined into every
 * admin route bundle (~15.7 MB server chunks) and made each admin request slow.
 * The lightweight id/name/count projection lives in
 * `src/data/admin-columns-meta.json` (generated by scripts/build-runtime-data.mjs).
 */
import adminMeta from "@/data/admin-columns-meta.json";

export type DisplayType = "single" | "image-list" | "text-list" | "news-list";
export type DataSource = "static" | "news-db" | "products" | "inquiries";

export type AdminColumn = {
  sourceId: number;
  name: string;
  displayType: DisplayType;
  dataSource: DataSource;
  parentId: number;
  itemCount: number;
};

export type AdminSection = {
  pid: number;
  name: string;
  nameEn: string;
  columns: AdminColumn[];
};

type AdminMeta = {
  categories: { sourceId: number; name: string; itemCount: number }[];
  contentCounts: Record<string, number>;
};

const meta = adminMeta as unknown as AdminMeta;
const adminCategories = meta.categories ?? [];
const contentCounts = meta.contentCounts ?? {};

function displayTypeFromKind(kind: string): DisplayType {
  switch (kind) {
    case "about": return "single";
    case "honor": return "image-list";
    case "down": return "news-list";
    case "lines": return "image-list";
    case "service": return "news-list";
    case "cases": return "image-list";
    default: return "text-list";
  }
}

function staticItemCount(sourceId: number): number {
  return contentCounts[String(sourceId)] ?? 0;
}

export function getAdminSections(): AdminSection[] {
  const count = (sourceId: number) => staticItemCount(sourceId);

  const sections: AdminSection[] = [
    {
      pid: 1,
      name: "关于我们",
      nameEn: "About Us",
      columns: [
        // 2026-10-01: 全部改为富文本文章模式（news-db）。原来每栏是一整块
        // 不可分割的富文本，没有列表也没有「+ 添加信息」，正是操作员反馈
        // “设计不行”的地方。现在与 新闻中心 → Employees Literary 完全一致。
        { sourceId: 13, name: "About Us", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        { sourceId: 55, name: "Main Products", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        { sourceId: 56, name: "Culture", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        { sourceId: 169, name: "Branch Companies", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        { sourceId: 171, name: "Factory & Warehouse", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        { sourceId: 172, name: "Course", displayType: "news-list", dataSource: "news-db", parentId: 1, itemCount: 0 },
        // Honor 已移到下面的「荣誉资质」区块（前台菜单里它属于 /honor，
        // 放在这里会让「关于我们 → Honor」和「荣誉资质 → Honor」两处风格不一致）。
      ],
    },
    {
      /**
       * 2026-10-02 新增。
       *
       * 前台菜单「荣誉资质 / Honor」下有 4 个栏目（Honor、Certificate、
       * To Customer、Certification Report），但后台侧边栏一直**没有**这个区块 ——
       * Certificate / To Customer / Certification Report 三栏的数据在
       * `admin_contents` 里有，前台 `/honor?id=…` 也能打开，后台却找不到入口，
       * 自然"没法编辑"。这里补齐，四栏统一走富文本文章模式。
       */
      pid: 5,
      name: "荣誉资质",
      nameEn: "Honor & Certificates",
      columns: [
        { sourceId: 16, name: "Honor", displayType: "news-list", dataSource: "news-db", parentId: 5, itemCount: 0 },
        { sourceId: 17, name: "Certificate", displayType: "news-list", dataSource: "news-db", parentId: 5, itemCount: 0 },
        { sourceId: 50, name: "To Customer", displayType: "news-list", dataSource: "news-db", parentId: 5, itemCount: 0 },
        { sourceId: 51, name: "Certification Report", displayType: "news-list", dataSource: "news-db", parentId: 5, itemCount: 0 },
      ],
    },
    {
      pid: 2,
      name: "新闻中心",
      nameEn: "News Center",
      columns: [
        { sourceId: 41, name: "Industry News", displayType: "news-list", dataSource: "news-db", parentId: 2, itemCount: 0 },
        { sourceId: 49, name: "Company News", displayType: "news-list", dataSource: "news-db", parentId: 2, itemCount: 0 },
        { sourceId: 52, name: "Employees Literary", displayType: "news-list", dataSource: "news-db", parentId: 2, itemCount: 0 },
      ],
    },
    {
      pid: 33,
      name: "产品展示",
      nameEn: "Products",
      columns: adminCategories.map((cat) => ({
        sourceId: cat.sourceId,
        name: cat.name,
        displayType: "text-list" as DisplayType,
        dataSource: "products" as DataSource,
        parentId: 33,
        itemCount: cat.itemCount,
      })),
    },
    {
      pid: 20,
      name: "其他",
      nameEn: "Other",
      columns: [
        { sourceId: 21, name: "banner-首页", displayType: "image-list", dataSource: "static", parentId: 20, itemCount: 0 },
        { sourceId: 31, name: "友情链接", displayType: "news-list", dataSource: "static", parentId: 20, itemCount: 0 },
        { sourceId: 47, name: "公司介绍-首页", displayType: "image-list", dataSource: "static", parentId: 20, itemCount: 0 },
      ],
    },
    {
      pid: 29,
      name: "联系我们",
      nameEn: "Contact Us",
      columns: [
        { sourceId: 32, name: "General Information", displayType: "news-list", dataSource: "static", parentId: 29, itemCount: 0 },
        { sourceId: 155, name: "Get Contacts", displayType: "single", dataSource: "static", parentId: 29, itemCount: 0 },
        { sourceId: 156, name: "Send Inquiry", displayType: "single", dataSource: "static", parentId: 29, itemCount: 0 },
        { sourceId: 162, name: "Give Advice To Seller", displayType: "single", dataSource: "static", parentId: 29, itemCount: 0 },
      ],
    },
    {
      pid: 42,
      name: "下载中心",
      nameEn: "Download Center",
      columns: [
        // 2026-10-01: 四栏改为富文本文章模式（news-db），后台使用与
        // 新闻中心 → Employees Literary 相同的「+ 添加信息」+ TipTap 编辑器。
        { sourceId: 43, name: "Company's Notice", displayType: "news-list", dataSource: "news-db", parentId: 42, itemCount: 0 },
        { sourceId: 76, name: "Technology Data Download", displayType: "news-list", dataSource: "news-db", parentId: 42, itemCount: 0 },
        { sourceId: 157, name: "Certificate Download", displayType: "news-list", dataSource: "news-db", parentId: 42, itemCount: 0 },
        { sourceId: 158, name: "MSDS Download", displayType: "news-list", dataSource: "news-db", parentId: 42, itemCount: 0 },
      ],
    },
    {
      pid: 44,
      name: "产品生产线",
      nameEn: "Production Lines",
      columns: [
        { sourceId: 45, name: "Packing Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(45) },
        { sourceId: 142, name: "BOPP Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(142) },
        { sourceId: 143, name: "BOPET Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(143) },
        { sourceId: 144, name: "Tape Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(144) },
        { sourceId: 149, name: "Thermal Lamination Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(149) },
        { sourceId: 164, name: "Bruckner Production Lines (Germany)", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(164) },
        { sourceId: 165, name: "Mitsubishi Production Lines (Japan)", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(165) },
        { sourceId: 167, name: "Copy Paper Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(167) },
        { sourceId: 173, name: "Silver Metallized Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(173) },
        { sourceId: 174, name: "POF Film Production Lines", displayType: "image-list", dataSource: "static", parentId: 44, itemCount: count(174) },
      ],
    },
    {
      pid: 53,
      name: "案例",
      nameEn: "Cases",
      columns: [
        // Managed as rich-text articles (same editor as 新闻中心), so operators
        // get "+ 添加信息" + the TipTap editor instead of the static card form.
        { sourceId: 54, name: "Development Cases", displayType: "news-list", dataSource: "news-db", parentId: 53, itemCount: 0 },
        // 2026-10-01: 这两栏原本是 image-list/static，正文无法编辑 —— 现改为文章模式。
        { sourceId: 145, name: "To Buyers", displayType: "news-list", dataSource: "news-db", parentId: 53, itemCount: 0 },
        { sourceId: 146, name: "To Markets", displayType: "news-list", dataSource: "news-db", parentId: 53, itemCount: 0 },
        { sourceId: 147, name: "To Ourselves", displayType: "news-list", dataSource: "news-db", parentId: 53, itemCount: 0 },
      ],
    },
    {
      pid: 78,
      name: "服务",
      nameEn: "Service",
      columns: [
        { sourceId: 79, name: "Useful Links Service", displayType: "news-list", dataSource: "static", parentId: 78, itemCount: count(79) },
        // Rich-text article columns (same editor as 新闻中心 → Employees Literary).
        { sourceId: 141, name: "Company Announcement", displayType: "news-list", dataSource: "news-db", parentId: 78, itemCount: 0 },
        { sourceId: 148, name: "Useful Knowledge", displayType: "news-list", dataSource: "news-db", parentId: 78, itemCount: 0 },
        { sourceId: 199, name: "Vessel Shipping Lines", displayType: "news-list", dataSource: "static", parentId: 78, itemCount: count(199) },
      ],
    },
    {
      pid: 90,
      name: "询盘管理",
      nameEn: "Inquiries",
      columns: [
        { sourceId: 90, name: "客户询盘", displayType: "news-list", dataSource: "inquiries", parentId: 90, itemCount: 0 },
      ],
    },
  ];

  return sections;
}

export function getDisplayTypeName(type: DisplayType): string {
  switch (type) {
    case "single": return "单页内容";
    case "image-list": return "图片列表";
    case "text-list": return "图文列表";
    case "news-list": return "新闻列表";
  }
}
