import { asc, eq, sql } from "drizzle-orm";
import { cache } from "react";

import validFilesList from "@/data/valid-files.json";
import { db } from "@/db";
import { adminContents, adminProducts } from "@/db/schema";
import { getCategories, productImageUrl } from "@/lib/site";
import type { HomeFeatured, HomeGalleryItem, HomePdf, HomeSummary, NavCategory } from "@/lib/site-summary";

/**
 * Home-page + mega-menu data computed from D1 at request time.
 *
 * `src/data/home-summary.json` and `src/data/site-nav.json` are generated by
 * `scripts/build-runtime-data.mjs` from the *static* `site-seed.json`, so
 * anything the admin panel changes (a renamed product, an uploaded PDF, a
 * product re-filed into another sub-category) never reached the home page
 * until the next deploy. This module rebuilds the same shape from
 * `admin_products` / `admin_contents` instead, so a change is visible on the
 * next page load.
 *
 * The build-time JSON is still used as the fallback: if D1 is unreachable or
 * empty the page renders exactly what it rendered before.
 */

type ProductRow = {
  sourceId: number;
  familyId: number;
  categoryId: number;
  title: string;
  titleZh: string;
  image: string;
  galleryJson: string;
  pdfsJson: string;
};

/** Legacy file names that actually exist, from `valid-files.json`. */
const validFiles = new Set(validFilesList as string[]);

function parseArray<T>(value: string | null | undefined, fallback: T[]): T[] {
  if (!value) return fallback;
  try {
    const parsed = JSON.parse(value) as unknown;
    return Array.isArray(parsed) ? (parsed as T[]) : fallback;
  } catch {
    return fallback;
  }
}

function galleryOf(row: ProductRow): string[] {
  const gallery = parseArray<string>(row.galleryJson, []);
  if (gallery.length > 0) return gallery;
  return row.image ? [row.image] : [];
}

/**
 * A PDF is worth linking when the file really exists: either it came from the
 * legacy library (`valid-files.json`) or it was uploaded through the admin
 * panel, in which case it is served from R2 under `/api/media/`.
 */
function isValidPdf(file?: string): boolean {
  if (!file) return false;
  if (file.startsWith("/api/media/")) return true;
  return validFiles.has(file.split("/").pop() ?? "");
}

/**
 * Live product rows, newest edit included.
 *
 * Wrapped in React's `cache` so the home page and `SiteHeader` (which renders
 * the mega-menu from the same rows) share one query per request instead of
 * running it twice.
 */
const loadRows = cache(async (): Promise<ProductRow[]> => {
  try {
    return await db
      .select({
        sourceId: adminProducts.sourceId,
        familyId: adminProducts.familyId,
        categoryId: adminProducts.categoryId,
        title: adminProducts.title,
        titleZh: adminProducts.titleZh,
        image: adminProducts.image,
        galleryJson: adminProducts.galleryJson,
        pdfsJson: adminProducts.pdfsJson,
      })
      .from(adminProducts)
      .where(sql`ifnull(${adminProducts.status}, '') <> '已删除'`)
      .orderBy(asc(adminProducts.sort), asc(adminProducts.sourceId));
  } catch (error) {
    console.error("[home-live] product query failed, falling back to the static seed:", error);
    return [];
  }
});

function groupByFamily(rows: ProductRow[]): Map<number, ProductRow[]> {
  const map = new Map<number, ProductRow[]>();
  for (const row of rows) {
    const bucket = map.get(row.familyId);
    if (bucket) bucket.push(row);
    else map.set(row.familyId, [row]);
  }
  return map;
}

/**
 * Mega-menu tree straight from the database.
 *
 * Family / sub-category *names* still come from the seed (they are curated
 * wording, not data), but every count, deep link and any sub-category that only
 * exists in the database is taken from `admin_products`, so a product moved or
 * added in the admin panel shows up without a redeploy.
 */
export async function getLiveCatalogTree(): Promise<NavCategory[] | null> {
  const rows = await loadRows();
  if (rows.length === 0) return null;

  const byFamily = groupByFamily(rows);
  const families = getCategories();
  const seeded = new Set<number>();
  const categories: NavCategory[] = [];

  const build = (
    familyId: number,
    name: string,
    nameZh: string,
    subs: { sourceId: number; name: string; nameZh: string }[],
  ): NavCategory => {
    const familyRows = byFamily.get(familyId) ?? [];
    const declared = new Set<number>();
    const navSubs = subs.map((sub) => {
      declared.add(sub.sourceId);
      const subRows = familyRows.filter((row) => row.categoryId === sub.sourceId);
      return {
        sourceId: sub.sourceId,
        name: sub.name,
        nameZh: sub.nameZh,
        firstItemId: subRows[0]?.sourceId ?? 0,
        count: subRows.length,
      };
    });
    // Sub-categories that only exist in the database (the admin panel can
    // re-file products into a sub the seed never declared).
    for (const row of familyRows) {
      if (declared.has(row.categoryId)) continue;
      declared.add(row.categoryId);
      const subRows = familyRows.filter((r) => r.categoryId === row.categoryId);
      navSubs.push({
        sourceId: row.categoryId,
        name: `Products ${row.categoryId}`,
        nameZh: `产品分类 ${row.categoryId}`,
        firstItemId: subRows[0]?.sourceId ?? 0,
        count: subRows.length,
      });
    }
    return {
      sourceId: familyId,
      name,
      nameZh,
      count: familyRows.length,
      sampleNames: familyRows.slice(0, 3).map((row) => row.title).filter(Boolean),
      sampleNamesZh: familyRows
        .slice(0, 3)
        .map((row) => row.titleZh || row.title)
        .filter(Boolean),
      subs: navSubs,
    };
  };

  for (const family of families) {
    seeded.add(family.sourceId);
    categories.push(
      build(
        family.sourceId,
        family.name,
        family.nameZh,
        family.subs.map((sub) => ({ sourceId: sub.sourceId, name: sub.name, nameZh: sub.nameZh })),
      ),
    );
  }

  // Families that only exist in the database.
  for (const [familyId] of byFamily) {
    if (seeded.has(familyId)) continue;
    categories.push(build(familyId, `Products ${familyId}`, `产品大类 ${familyId}`, []));
  }

  return categories;
}

/** Live "about us" body in Chinese (content column 13). */
async function aboutZhHtml(fallback: string): Promise<string> {
  try {
    const [row] = await db
      .select({ dataJson: adminContents.dataJson })
      .from(adminContents)
      .where(eq(adminContents.sourceId, 13))
      .limit(1);
    if (!row) return fallback;
    const data = JSON.parse(row.dataJson) as {
      items?: Record<string, unknown>;
      itemsZh?: Record<string, unknown>;
    };
    const html = (data.itemsZh?.bodyHtml as string) || (data.items?.bodyHtml as string) || "";
    return html || fallback;
  } catch {
    return fallback;
  }
}

/**
 * Home-page summary from D1, falling back to the build-time JSON.
 *
 * `fallback` is `home-summary.json`; it is returned untouched when the database
 * has nothing to say, so the page never breaks because of D1.
 */
export async function getHomeSummaryLive(fallback: HomeSummary): Promise<HomeSummary> {
  const rows = await loadRows();
  if (rows.length === 0) return fallback;

  try {
    const byFamily = groupByFamily(rows);
    const families = getCategories();

    const categories = (await getLiveCatalogTree()) ?? fallback.categories;

    const featured: HomeFeatured[] = [];
    const gallery: HomeGalleryItem[] = [];
    const pdfs: HomePdf[] = [];
    const seenPdfs = new Set<string>();

    for (const family of families) {
      const familyRows = byFamily.get(family.sourceId) ?? [];

      // Featured: first product of the family that has a picture.
      if (featured.length < 10) {
        const withGallery = familyRows.find((row) => galleryOf(row).length > 0);
        if (withGallery) {
          featured.push({
            category: {
              sourceId: family.sourceId,
              name: family.name,
              nameZh: family.nameZh,
            },
            product: {
              sourceId: withGallery.sourceId,
              title: withGallery.title,
              titleZh: withGallery.titleZh || withGallery.title,
              gallery0: productImageUrl(galleryOf(withGallery)[0] ?? ""),
            },
          });
        }
      }

      for (const row of familyRows) {
        for (const image of galleryOf(row)) {
          if (gallery.length >= 8) break;
          gallery.push({ src: productImageUrl(image), title: row.title || family.name });
        }
        for (const pdf of parseArray<{ file?: string; label?: string }>(row.pdfsJson, [])) {
          if (pdfs.length >= 30 || !pdf?.file || seenPdfs.has(pdf.file)) continue;
          if (!isValidPdf(pdf.file)) continue;
          seenPdfs.add(pdf.file);
          pdfs.push({ label: pdf.label ?? "", file: pdf.file, product: row.title || family.name });
        }
      }
    }

    return {
      categories,
      featured,
      gallery,
      pdfs,
      totalProducts: rows.length,
      aboutZhHtml: await aboutZhHtml(fallback.aboutZhHtml),
    };
  } catch (error) {
    console.error("[home-live] falling back to the build-time summary:", error);
    return fallback;
  }
}
